### ISSUE TITLE
Want to say hello

### ISSUE THREAD

**Issue by cuihantao** [epzgwu2017/PowerSimu#1]
Hi there,

I found your repository a while ago. I guess you are also trying to implement a power system simulator based on Dr. Federico Milano's book and PSAT. 

It seems that you have a team. Are you still working on this?

**Comment by Yuweizhou123** [comment]
Yes, I have a team and we want to do something about power system simulator. I found that you have done a lot of job in this aspect. Are you going to improve Andes?

**Comment by cuihantao** [comment]
Yes, it's in progress, but I'm the only one currently developing it. I How
are you going to continue your project?


Regards,
Hantao Cui

Office: 865-974-5493

**Comment by Yuweizhou123** [comment]
I want to implement a power system simulation toolbox and I can use it to do some research which I'm interested. But I have no idea now because the structure of my project is poor. I have to sort out what has been done before considering the next step. May be I need to determine a more flexible structure. You are professional , and may be you can give me some advice. And what do you want to implement? By the way, how long have you spent to develop Andes?

**Comment by cuihantao** [comment]
Glad to hear that. You can find me on WeChat if you use that. My username
is cuihantao. We can talk about a promising simulator in detail.
